/* Generated by Amaranth Yosys 0.35 (PyPI ver 0.35.0.0.post81, git sha1 cc31c6ebc) */

(* top =  1  *)
(* generator = "Amaranth" *)
module tt_um_cmerrill_test(uo_out, uio_in, uio_out, uio_oe, ena, clk, rst_n, ui_in);
  reg \$auto$verilog_backend.cc:2189:dump_module$1  = 0;
  (* src = "C:\\Users\\chris\\Documents\\Projects\\tt06-cmerrill\\src\\tt_um_cmerrill_test.py:30" *)
  wire \$2 ;
  (* src = "C:\\Users\\chris\\Documents\\Projects\\tt06-cmerrill\\src\\tt_um_cmerrill_test.py:41" *)
  wire [8:0] \$4 ;
  (* src = "C:\\Users\\chris\\Documents\\Projects\\tt06-cmerrill\\src\\tt_um_cmerrill_test.py:41" *)
  wire [8:0] \$5 ;
  (* src = "C:\\Users\\chris\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\amaranth\\lib\\wiring.py:1647" *)
  input clk;
  wire clk;
  (* src = "C:\\Users\\chris\\Documents\\Projects\\tt06-cmerrill\\src\\tt_um_cmerrill_test.py:27" *)
  wire \clk$1 ;
  (* src = "C:\\Users\\chris\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\amaranth\\lib\\wiring.py:1647" *)
  input ena;
  wire ena;
  (* src = "C:\\Users\\chris\\Documents\\Projects\\tt06-cmerrill\\src\\tt_um_cmerrill_test.py:27" *)
  wire rst;
  (* src = "C:\\Users\\chris\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\amaranth\\lib\\wiring.py:1647" *)
  input rst_n;
  wire rst_n;
  (* src = "C:\\Users\\chris\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\amaranth\\lib\\wiring.py:1647" *)
  input [7:0] ui_in;
  wire [7:0] ui_in;
  (* src = "C:\\Users\\chris\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\amaranth\\lib\\wiring.py:1647" *)
  input [7:0] uio_in;
  wire [7:0] uio_in;
  (* src = "C:\\Users\\chris\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\amaranth\\lib\\wiring.py:1647" *)
  output [7:0] uio_oe;
  wire [7:0] uio_oe;
  (* src = "C:\\Users\\chris\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\amaranth\\lib\\wiring.py:1647" *)
  output [7:0] uio_out;
  wire [7:0] uio_out;
  (* src = "C:\\Users\\chris\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\amaranth\\lib\\wiring.py:1647" *)
  output [7:0] uo_out;
  reg [7:0] uo_out = 8'h00;
  (* src = "C:\\Users\\chris\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\amaranth\\lib\\wiring.py:1647" *)
  reg [7:0] \uo_out$next ;
  assign \$2  = ~ (* src = "C:\\Users\\chris\\Documents\\Projects\\tt06-cmerrill\\src\\tt_um_cmerrill_test.py:30" *) rst_n;
  assign \$5  = ui_in + (* src = "C:\\Users\\chris\\Documents\\Projects\\tt06-cmerrill\\src\\tt_um_cmerrill_test.py:41" *) uio_in;
  always @(posedge \clk$1 )
    uo_out <= \uo_out$next ;
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$1 ) begin end
    \uo_out$next  = \$5 [7:0];
    (* src = "C:\\Users\\chris\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\amaranth\\hdl\\xfrm.py:503" *)
    casez (rst)
      1'h1:
          \uo_out$next  = 8'h00;
    endcase
  end
  assign \$4  = \$5 ;
  assign uio_out = 8'h00;
  assign uio_oe = 8'h00;
  assign rst = \$2 ;
  assign \clk$1  = clk;
endmodule
